# Generated by Django 3.1.7 on 2021-03-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleApp', '0002_auto_20210305_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timing',
            old_name='timing',
            new_name='timing1',
        ),
        migrations.AddField(
            model_name='timing',
            name='timing2',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
