# Generated by Django 3.1.7 on 2021-03-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleApp', '0003_auto_20210307_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='timings',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
